# Climate-Adaptive Seed AI Bank Configuration

# Database Configuration
database:
  postgresql:
    host: "localhost"
    port: 5432
    database: "seedbank_db"
    username: "seedbank_user"
    password: "your_password_here"
    
  mongodb:
    host: "localhost"
    port: 27017
    database: "seedbank_models"
    username: "mongo_user"
    password: "your_password_here"
    
  influxdb:
    host: "localhost"
    port: 8086
    database: "sensor_data"
    username: "influx_user"
    password: "your_password_here"
    token: "your_influx_token_here"
    org: "seedbank_org"
    
  redis:
    host: "localhost"
    port: 6379
    password: "your_redis_password"
    db: 0

# External API Configuration
external_apis:
  weather:
    unma:
      base_url: "https://api.unma.gov.ug/v1"
      api_key: "your_unma_api_key"
    
    openweather:
      base_url: "https://api.openweathermap.org/data/2.5"
      api_key: "your_openweather_api_key"
  
  satellite:
    nasa_modis:
      base_url: "https://modis.gsfc.nasa.gov/data/dataprod/"
      username: "your_nasa_username"
      password: "your_nasa_password"

# Model Configuration
models:
  ensemble:
    model_weights:
      climate_compatibility: 0.35
      yield_prediction: 0.40
      risk_assessment: 0.25
    
    hyperparameters:
      random_forest:
        n_estimators: 100
        max_depth: 10
        random_state: 42
      
      gradient_boosting:
        n_estimators: 200
        learning_rate: 0.1
        max_depth: 6
    
    training:
      validation_split: 0.2
      cross_validation_folds: 5
      early_stopping_patience: 10

# IoT Configuration
iot:
  mqtt:
    broker: "mqtt.seedbank.uganda.ai"
    port: 1883
    username: "iot_client"
    password: "your_mqtt_password"
    topics:
      sensor_data: "sensors/+/data"
      device_status: "sensors/+/status"
      alerts: "alerts/+"
  
  lorawan:
    gateway_eui: "your_gateway_eui"
    network_session_key: "your_network_session_key"
    app_session_key: "your_app_session_key"
  
  data_collection:
    batch_size: 1000
    buffer_time_seconds: 300
    retry_attempts: 3

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  
  authentication:
    secret_key: "your_secret_key_here_make_it_long_and_secure"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
  
  rate_limiting:
    requests_per_minute: 60
    burst_limit: 100
  
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["GET", "POST", "PUT", "DELETE"]

# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  
  files:
    main: "logs/seedbank.log"
    errors: "logs/errors.log"
    iot: "logs/iot_data.log"
    api: "logs/api_requests.log"
  
  rotation: "1 day"
  retention: "30 days"

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    port: 9090
    
  alerts:
    email:
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: "alerts@seedbank.uganda.ai"
      password: "your_email_password"
      recipients: ["admin@seedbank.uganda.ai"]
    
    slack:
      webhook_url: "your_slack_webhook_url"
      channel: "#seedbank-alerts"
  
  health_checks:
    database_timeout: 5
    api_timeout: 3
    model_response_time: 2

# Deployment Configuration
deployment:
  environment: "development"  # development, staging, production
  
  scaling:
    min_replicas: 2
    max_replicas: 10
    cpu_threshold: 70
    memory_threshold: 80
  
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
    storage_location: "backups/"

# Security Configuration
security:
  encryption:
    data_at_rest: true
    algorithm: "AES-256"
    key_rotation_days: 90
  
  ssl:
    enabled: true
    cert_file: "certs/seedbank.crt"
    key_file: "certs/seedbank.key"
  
  data_privacy:
    anonymize_logs: true
    data_retention_days: 2555  # 7 years
    consent_required: true

# Feature Flags
features:
  advanced_ml_models: true
  real_time_recommendations: true
  satellite_integration: true
  mobile_offline_mode: true
  multi_language_support: false
  blockchain_verification: false

# Regional Settings
regional:
  default_country: "uganda"
  default_timezone: "Africa/Kampala"
  default_currency: "UGX"
  default_language: "en"
  
  supported_regions:
    - "central"
    - "eastern"
    - "northern" 
    - "western"

# Economic Parameters
economics:
  default_seed_costs:
    maize: 12.0  # USD per kg
    beans: 8.0
    rice: 10.0
    cassava: 3.0
  
  default_prices:
    maize: 200.0  # USD per ton
    beans: 800.0
    rice: 600.0
    cassava: 150.0
  
  production_costs:
    per_hectare: 300.0  # USD
    
  risk_factors:
    drought_penalty: 0.15
    disease_penalty: 0.10
    market_penalty: 0.05